config/routes.rb
Rails.application.routes.draw do
  get 'cuentas/index'

  get 'venta/edit'

  get 'user/edit'

  get 'user/new'

  get 'user/show'

  get 'static_pages/home'

  get 'sessions/new'

  get 'inventario/edit'

  get 'inventario/index'

  get 'inventario/new'

  get 'inventario/show'

  get 'embarque/edit'

  get 'embarque/index'

  get 'embarque/new'

  get 'venta/edit'
  resources :inventario
  resources :cliente
  resources :embarque
  resources :cotizacion
  resources :venta
  resources :ventuminventario
  resources :cotizacioninventario
    get 'sessions/new'
  root                  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'help'      =>  'static_pages#help'
  get     'contact'   =>  'static_pages#contact'
  get     'cuentas'   =>  'static_pages#cuentas_cobrar'
  get     'signup'    =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
require 'csv'
	validates :nombre, :telefono, :email, :direccion, :direccion_entrega,   presence: true
	def self.to_csv(options = {})
			CSV.generate(options) do |csv|
				csv << column_names
				all.each do |i|
					csv << i.attributes.values_at(*column_names)
				end
			end
	end
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
	has_many :cotizacions_inventarios
  	has_many :inventarios, through: :cotizacions_inventarios
end

app/models/cotizacion_inventario.rb
class CotizacionInventario < ApplicationRecord
	belongs_to :cotizacion
  	belongs_to :inventario
end

app/models/embarque.rb
class Embarque < ApplicationRecord
	validates :numero_guia, :transportista, :fecha_salida, :numero_orden, :destino, :cliente, :status, presence: true
end

app/models/inventario.rb
class Inventario < ApplicationRecord
	has_many :cotizacions_inventarios
  	has_many :cotizacions, through: :cotizacions_inventarios
  	has_many :venta_inventarios
  	has_many :venta, through: :venta_inventarios
	validates :upc, :unidad_medida, :tipo, :bodega, :modelo, :descripcion, :compra, :p_venta, :cantidad,   presence: true
	def self.to_csv(options = {})
			CSV.generate(options) do |csv|
				csv << column_names
				all.each do |i|
					csv << i.attributes.values_at(*column_names)
				end
			end
	end

end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name,   presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates :email , presence: true, length: { maximum: 255 },
										 format: { with: VALID_EMAIL_REGEX },
										 uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum:6 }

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

end

app/models/ventum.rb
class Ventum < ApplicationRecord
	has_many :venta_inventarios
  	has_many :inventarios, through: :venta_inventarios
end

app/models/ventum_inventario.rb
class VentumInventario < ApplicationRecord
	belongs_to :inventario
  	belongs_to :ventum
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.id.to_s == params[:id]
  	  @user = User.find(params[:id])
    else
      redirect_to posts_path
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		flash[:success] = "Bienvenido a Paycesa"
      login_url(@user)
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil creado"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  def new
  	x = ""
  	x = params[:tc][:tc] unless params[:tc].nil?
  	if x == "yes"
  		@tc_tc = rand(1000000000000)
  		@venta = Ventum.new(tc: @tc_tc, cliente: "", bodega:"", pago: "", cantidad: 0, descuento: 0)
  		@venta.save!
  	end
  	@venta = Ventum.last
  	render 'edit'
  end

  def create
  end

  def index
    @venta = Ventum.last
    @movs = VentumInventario.where(ventum_id: @venta.id) 
  end

  def show
    @venta = Ventum.last
    productos = []
    @movs = VentumInventario.where(ventum_id: @venta.id) 
    @movs.each do |mov|
        productos << inventario = Inventario.find(mov.inventario_id)
    end
    respond_to do |format|
      format.html
      format.pdf do
        pdf =  OrderPdf.new(@venta, @movs, productos, "Venta")
        send_data pdf.render, filename: "venta_#{@venta.tc}.pdf", type: "application/pdf", disposition: "inline"
      end
    end

  end

  def update
    venta = Ventum.find(params[:id])
    productos = VentumInventario.where(ventum_id: venta.id)
    suma = 0
    productos.each do |producto|
      inventario = Inventario.find_by(id: producto.inventario_id)
      suma = suma + (inventario.p_venta * producto.c_productos)
      if inventario.cantidad < venta.cantidad
        flash[:danger] = "La venta no tiene suficiente inventario"
        redirect_to new_ventum_path
      end
    end
    subtotal =  suma
    descuento =  ((subtotal / 100 ) * params[:ventum][:descuento].to_f)
    total = ((subtotal-descuento) * 1.16)
    iva = (subtotal-descuento)*0.16

    if venta.subtotal == nil 
      venta.update_attributes(cliente: params[:ventum][:cliente], bodega: params[:ventum][:bodega], pago: params[:ventum][:pago], subtotal: subtotal, descuento: descuento, iva: iva, total: total, status: "completada")
      redirect_to ventum_path(Ventum.last)
    else
      redirect_to ventuminventario_index_path
    end
  end

  def destroy
    VentumInventario.find_by(ventum_id: Ventum.last.id, inventario_id: params[:id]).destroy
    redirect_to new_ventum_path
  end

  private
  	def venta_params
  		params.require(:ventum).permit(:tc, :cliente, :bodega, :pago, :subtotal, :descuento, :iva, :total, :status)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/cotizacion_helper.rb
module CotizacionHelper
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/helpers/embarque_helper.rb
module EmbarqueHelper
end

app/helpers/inventario_helper.rb
module InventarioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])	
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
		
	end
	
	def logged_in?
		!current_user.nil?		
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)		
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil		
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#return the gravatar
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.upcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/venta/edit.html.erb
<h1 class="text-center">Venta</h1>
<br><br>
<div class="row">
	<h4>#TC:<%="#{Ventum.last.tc}"%></h4>
	</div>
	<hr>
<div class="row col-sm-12">


	<table class="table table-striped " style="background-color: #b3e6ff" id="myTable">
		<input type="text" class="form-control col-sm-4" id="myInput" onkeyup="myFunction()" placeholder="Buscar.." title="Type in a name">

		<thead>
			<tr>
				<th scope="col">UPC</th>
	      <th scope="col">Modelo</th>
	      <th scope="col">Descripción</th>
	      <th scope="col">Compra</th>
	      <th scope="col">Venta</th>
	      <th scope="col">Cantidad Existencia</th>
	      <th scope="col">Bodega</th>
	      <th scope="col">Agregar al carrito</th>
			</tr>
		</thead>
		<tbody>
			
			<% if Inventario.all.empty? %>
				<h3 class="text-center">No hay inventario</h3>
			<% else %>
				<% Inventario.all.each do|item|%>
					<tr>
						<td scope="col"><%= item.upc %></td>
						<td scope="col"><%= item.modelo %></td>
						<td scope="col"><%= item.descripcion %></td>
						<td scope="col"><%= item.compra %></td>
						<td scope="col"><%= item.p_venta %></td>
						<td scope="col"><%= if item.cantidad > 0 then item.cantidad else "SIN EXISTENCIA" end %></td>
						<td scope="col"><%= item.bodega %></td>
						<td scope="col"><%= link_to "Elige este producto", ventuminventario_path(item), class: "btn btn-primary" %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<%= link_to "Ir al los detalles de la venta", venta_path, class: "btn btn-primary" %>
</div>






<script type="text/javascript">
	function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}

</script>

app/views/venta/index.html.erb
<h1 class="text-center">Llena los detalles de la venta</h1>
<div class="row col-sm-12">
		<%= render 'layouts/detalle' %>
</div>

app/views/venta/show.html.erb
<h1 class="text-center">Llena los detalles de la venta</h1>

	<% clientes = [] %>
	      <% Cliente.all.each { |item| clientes << [item.nombre, item.nombre]} %>
<%= form_for Ventum.last do |f|%>
		<%= f.label "# TC" %><br>	
	  <%= f.text_field "tc", value: Ventum.last.tc, class: "form-control", disabled: true , id: 'tc'%>

		 <br><br><br>
<div class="offset-sm-1 col-sm-10">  
  <%= f.label "Cliente" %><br>
  <%= f.select("cliente", clientes, {} ,{class: "form-control"}) %><br>  
  <%= f.label "Bodega" %><br>
  <%= f.select("bodega", [['Ramos Millan', 'ramos'], ['Texcoco', 'texcoco'], ['Veloz', 'veloz']], {} ,{class: "form-control"}) %><br>
  <%= f.label "Pago" %><br>
  <%= f.select("pago", [['Contado', 'contado'], ['Crédito', 'credito']], {} ,{class: "form-control"}) %><br>
  <%= f.label "Descuento" %><br>     
	<%= f.text_field "descuento", class: "form-control" %><br>
<%= f.submit "Aceptar", class: "btn btn-primary formulario" %><br></div>
<% end %>
<%= link_to "Generar pdf", ventum_path(Ventum.last ,format: "pdf"),  target: '_blank', class: "btn btn-outline-primary offset-sm-1 col-sm-1" %>