config/routes.rb
Rails.application.routes.draw do
  get 'cuentas/index'

  get 'venta/edit'

  get 'user/edit'

  get 'user/new'

  get 'user/show'

  get 'static_pages/home'

  get 'sessions/new'

  get 'inventario/edit'

  get 'inventario/index'

  get 'inventario/new'

  get 'inventario/show'

  get 'embarque/edit'

  get 'embarque/index'

  get 'embarque/new'

  get 'venta/edit'
  resources :inventario
  resources :cliente
  resources :embarque
  resources :cotizacion
  resources :venta
  resources :ventuminventario
  resources :cotizacioninventario
    get 'sessions/new'
  root                  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'help'      =>  'static_pages#help'
  get     'contact'   =>  'static_pages#contact'
  get     'cuentas'   =>  'static_pages#cuentas_cobrar'
  get     'signup'    =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  resources :users

end

app/models/cliente.rb
class Cliente < ApplicationRecord
require 'csv'
	validates :nombre, :telefono, :email, :direccion, :direccion_entrega,   presence: true
	def self.to_csv(options = {})
			CSV.generate(options) do |csv|
				csv << column_names
				all.each do |i|
					csv << i.attributes.values_at(*column_names)
				end
			end
	end
end

app/controllers/cliente_controller.rb
class ClienteController < ApplicationController

  def index
    @clientes = Cliente.all
    respond_to do |format|
      format.html
      format.csv{ send_data  @clientes.to_csv  }
      format.xls{ send_data  @clientes.to_csv(col_sep: "\t") }
    end
  end

  def new
    @cliente = Cliente.new
  end
  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      flash[:success] = "Cliente guardado"
      #flash[:success] = "Welcome to my app"
      #log_in(@)
      redirect_to cliente_index_path
    else
      flash[:danger] = "Todos los campos deben estar llenos"
      render 'new'
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])
    if @cliente.update_attributes(cliente_params)
      flash[:success] = "Cliente actualizado"
      #flash[:success] = "Profile updated"
      redirect_to cliente_index_path
    else
      flash[:danger] = "Todos los campos deben estar llenos"
      render 'edit'
    end
  end

  def show
    
  end

  def destroy
    Cliente.find(params[:id]).destroy
    flash[:success] = "Cliente borrado"
    redirect_to cliente_index_path
  end

  private
    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :email, :direccion, :direccion_entrega)
    end
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/views/cliente/edit.html.erb
	<h1 class="text-center">Edita el cliente</h1>
	<br><br>
<div class="offset-sm-1 col-sm-10 form">
	<%= form_for(@cliente) do |f|%>
		 <%= f.label "Nombre" %><br>	
	  <%= f.text_field "nombre", type: "text", class: "form-control" %>
	  <%= f.label "Teléfono" %><br>	
	  <%= f.text_field "telefono", type: "text", class: "form-control" %>
	  <%= f.label "Email" %><br>
	  <%= f.text_field "email", type: "email", class: "form-control" %>
	  <%= f.label "Dirección" %><br>
	  <%= f.text_area "direccion", type: "text", class: "form-control" %>
	  <%= f.label "Dirección de Entrega" %><br>	
	  <%= f.text_area "direccion_entrega", type: "text", class: "form-control" %><br>
	  <%= f.submit "Actualizar", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/cliente/index.html.erb
<h1 class="text-center">Clientes</h1>
<br><br>
<div class="row">
	<%=  link_to "Agregar cliente", new_cliente_path, class: "btn btn-outline-primary offset-sm-6 col-sm-2 "%>
	<%= link_to "Excel", cliente_index_path(format: "xls"), class: "btn btn-outline-primary offset-sm-1 col-sm-1" %>
	</div>
<div class="row col-sm-12">

	
	<table class="table table-striped " style="background-color: #b3e6ff" id="myTable">
		<input type="text" class="form-control col-sm-4" id="myInput" onkeyup="myFunction()" placeholder="Buscar.." title="Type in a name">

		<thead>
			<tr>
				<th scope="col">ID#</th>
	      <th scope="col">Nombre</th>
	      <th scope="col">Teléfono</th>
	      <th scope="col">Email</th>
	      <th scope="col">Update</th>
	      <th scope="col">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% if @clientes.empty? %>
				<h3 class="text-center">No hay clientes</h3>
			<% else %>
				<% @clientes.each do|item|%>
					<tr>
						<td scope="col"><%= item.id %></td>
						<td scope="col"><%= item.nombre %></td>
						<td scope="col"><%= item.telefono %></td>
						<td scope="col"><%= item.email %></td>
						<td scope="col"> <%= link_to "Update", edit_cliente_path(item), class: "btn btn-primary" %> </td>
						<td scope="col"> <%= link_to "Delete", cliente_path(item), method: "delete", data: { confirm: "Are you sure?" } , class: "btn btn-primary" %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

app/views/cliente/new.html.erb
<h1 class="text-center">Clientes</h1>
<%= render 'layouts/create_cliente' %>