config/routes.rb
Rails.application.routes.draw do
  get 'cuentas/index'

  get 'venta/edit'

  get 'user/edit'

  get 'user/new'

  get 'user/show'

  get 'static_pages/home'

  get 'sessions/new'

  get 'inventario/edit'

  get 'inventario/index'

  get 'inventario/new'

  get 'inventario/show'

  get 'embarque/edit'

  get 'embarque/index'

  get 'embarque/new'

  get 'venta/edit'
  resources :inventario
  resources :cliente
  resources :embarque
  resources :cotizacion
  resources :venta
  resources :ventuminventario
  resources :cotizacioninventario
    get 'sessions/new'
  root                  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'help'      =>  'static_pages#help'
  get     'contact'   =>  'static_pages#contact'
  get     'cuentas'   =>  'static_pages#cuentas_cobrar'
  get     'signup'    =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  resources :users

end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
	has_many :cotizacions_inventarios
  	has_many :inventarios, through: :cotizacions_inventarios
end

app/controllers/cotizacion_controller.rb
class CotizacionController < ApplicationController
  def new
  	x = ""
  	x = params[:tc][:tc] unless params[:tc].nil?
  	if x == "yes"
  		@tc_tc = rand(1000000000000)
  		@cotizacion = Cotizacion.new(tc: @tc_tc, cliente: "", bodega:"", pago: "", cantidad: 0, descuento: 0)
  		@cotizacion.save!
  	end
  	@clientes = Cliente.all
  	@cotizacion = Cotizacion.last
  	render 'edit'
  end

  def index
    @cotizacion = Cotizacion.last
    @movs = CotizacionInventario.where(cotizacion_id: @cotizacion.id) 
  end

  def show
    @cotizacion = Cotizacion.last
    productos = []
    @movs = CotizacionInventario.where(cotizacion_id: @cotizacion.id) 
    @movs.each do |mov|
        productos << inventario = Inventario.find(mov.inventario_id)
    end
    respond_to do |format|
      format.html
      format.pdf do
        pdf =  OrderPdf.new(@cotizacion, @movs, productos, "Cotizacion")
        send_data pdf.render, filename: "cotizacion_#{@cotizacion.tc}.pdf", type: "application/pdf", disposition: "inline"
      end
    end

  end

  def update
    cotizacion = Cotizacion.find(params[:id])
    productos = CotizacionInventario.where(cotizacion_id: cotizacion.id)
    suma = 0
    productos.each do |producto|
      inventario = Inventario.find_by(id: producto.inventario_id)
      suma = suma + (inventario.p_venta * producto.c_productos)
    end
    subtotal =  suma
    descuento =  ((subtotal / 100 ) * params[:cotizacion][:descuento].to_f)
    total = ((subtotal-descuento) * 1.16)
    iva = (subtotal-descuento)*0.16

    if cotizacion.subtotal == nil 
      cotizacion.update_attributes(cliente: params[:cotizacion][:cliente], bodega: params[:cotizacion][:bodega], pago: params[:cotizacion][:pago], subtotal: subtotal, descuento: descuento, iva: iva, total: total, status: "completada")
      redirect_to cotizacion_path(Cotizacion.last)
    else
      redirect_to cotizacioninventario_index_path
    end
  end

  def destroy
    CotizacionInventario.find_by(cotizacion_id: cotizacion.last.id, inventario_id: params[:id]).destroy
    redirect_to new_cotizacion_path
  end

  private
    def cotizacion_params
      params.require(:cotizacion).permit(:tc, :cliente, :bodega, :pago, :subtotal, :descuento, :iva, :total, :status)
    end
end

app/helpers/cotizacion_helper.rb
module CotizacionHelper
end

app/views/cotizacion/edit.html.erb
<h1 class="text-center">Cotización</h1>
<br><br>
<div class="row">
	<h4>#TC:<%="#{Cotizacion.last.tc}"%></h4>
	</div>
	<hr>
<div class="row col-sm-12">


	<table class="table table-striped " style="background-color: #b3e6ff" id="myTable">
		<input type="text" class="form-control col-sm-4" id="myInput" onkeyup="myFunction()" placeholder="Buscar.." title="Type in a name">

		<thead>
			<tr>
				<th scope="col">UPC</th>
	      <th scope="col">Modelo</th>
	      <th scope="col">Descripción</th>
	      <th scope="col">Compra</th>
	      <th scope="col">Venta</th>
	      <th scope="col">Cantidad Existencia</th>
	      <th scope="col">Bodega</th>
	      <th scope="col">Agregar al carrito</th>
			</tr>
		</thead>
		<tbody>
			
			<% if Inventario.all.empty? %>
				<h3 class="text-center">No hay inventario</h3>
			<% else %>
				<% Inventario.all.each do|item|%>
					<tr>
						<td scope="col"><%= item.upc %></td>
						<td scope="col"><%= item.modelo %></td>
						<td scope="col"><%= item.descripcion %></td>
						<td scope="col"><%= item.compra %></td>
						<td scope="col"><%= item.p_venta %></td>
						<td scope="col"><%= if item.cantidad > 0 then item.cantidad else "SIN EXISTENCIA" end %></td>
						<td scope="col"><%= item.bodega %></td>
						<td scope="col"><%= link_to "Elige este producto", cotizacioninventario_path(item), class: "btn btn-primary" %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<%= link_to "Ir al los detalles de la venta", cotizacion_index_path, class: "btn btn-primary" %>
</div>






<script type="text/javascript">
	function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}

</script>

app/views/cotizacion/index.html.erb
<h1 class="text-center">Llena los detalles de la cootización</h1>
<div class="row col-sm-12">
		<%= render 'layouts/cotiza' %>
</div>

app/views/cotizacion/show.html.erb
<h1 class="text-center">Detalles de su cotización</h1>
<h3>Tc: <%= @cotizacion.tc %></h3>
<h3>Cliente: <%= @cotizacion.cliente %></h3>
<h3>Tipo pago: <%= @cotizacion.pago %></h3>
<h3>Fecha: <%= @cotizacion.created_at %></h3>
<h3>Cantidad: <%= @cotizacion.cantidad %></h3>
<h3>Descuento: <%= @cotizacion.descuento %></h3>

<%= link_to "Generar pdf", cotizacion_path(@cotizacion ,format: "pdf"),  target: '_blank', class: "btn btn-outline-primary offset-sm-1 col-sm-1" %>