config/routes.rb
Rails.application.routes.draw do
  get 'cuentas/index'

  get 'venta/edit'

  get 'user/edit'

  get 'user/new'

  get 'user/show'

  get 'static_pages/home'

  get 'sessions/new'

  get 'inventario/edit'

  get 'inventario/index'

  get 'inventario/new'

  get 'inventario/show'

  get 'embarque/edit'

  get 'embarque/index'

  get 'embarque/new'

  get 'venta/edit'
  resources :inventario
  resources :cliente
  resources :embarque
  resources :cotizacion
  resources :venta
  resources :ventuminventario
  resources :cotizacioninventario
    get 'sessions/new'
  root                  'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'help'      =>  'static_pages#help'
  get     'contact'   =>  'static_pages#contact'
  get     'cuentas'   =>  'static_pages#cuentas_cobrar'
  get     'signup'    =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  resources :users

end

app/models/embarque.rb
class Embarque < ApplicationRecord
	validates :numero_guia, :transportista, :fecha_salida, :numero_orden, :destino, :cliente, :status, presence: true
end

app/controllers/embarque_controller.rb
class EmbarqueController < ApplicationController
	def index
  	@embarques = Embarque.all
  end

  def new
  	@clientes = Cliente.all
  	@embarque = Embarque.new
  end
  def create
  	@embarque = Embarque.new(embarque_params)

  	if @embarque.save
      flash[:success] = "Embarque guardado"
  		#flash[:success] = "Welcome to my app"
      #log_in(@)
  		redirect_to embarque_index_path
  	else
      flash[:danger] = "Todos los campos deben estar llenos"
  		render 'new'
  	end
  end

  def edit
  	@clientes = Cliente.all
    @embarque = Embarque.find(params[:id])
  end

  def update
    @embarque = Embarque.find(params[:id])
    if @embarque.update_attributes(embarque_params)
      flash[:success] = "Embarque actualizado"
      #flash[:success] = "Profile updated"
      redirect_to embarque_index_path
    else
      flash[:danger] = "Todos los campos deben estar llenos"
      render 'edit'
    end
  end

  def destroy
		Embarque.find(params[:id]).destroy
		flash[:success] = "Embarque borrado"
		redirect_to embarque_index_path
	end

  private
  	def embarque_params
  		params.require(:embarque).permit(:numero_guia, :transportista, :fecha_salida, :numero_orden, :destino, :cliente, :status)
  	end
end

app/helpers/embarque_helper.rb
module EmbarqueHelper
end

app/views/embarque/edit.html.erb
<h1 class="text-center">Edita el cliente</h1>
<br><br>
<% clientes = [] %>
<% if !@clientes.nil? %>
	<% @clientes.each { |item| clientes << [item.nombre, item.nombre]} %>
<% end %>
<div class="offset-sm-1 col-sm-10 form">
<%= form_for(@embarque) do |f|%>
	<%= f.label "# de Guía" %><br>	
	<%= f.text_field "numero_guia", type: "text", class: "form-control" %>
	<%= f.label "Transportista" %><br>
	<%= f.text_field "transportista", type: "text", class: "form-control" %>	
  <%= f.label "Fecha de Salida" %><br>	
  <%= f.date_field "fecha_salida", class: "form-control" %>
  <%= f.label "Ordén" %><br>	
  <%= f.text_field "numero_orden", type: "text", class: "form-control" %>
  <%= f.label "Destino" %><br>
  <%= f.text_field "destino", type: "text", class: "form-control" %>
  <%= f.label "Cliente" %><br>
  <%= f.select("cliente", clientes, {} ,{class: "form-control"}) %><br>
  <%= f.label "Status" %><br>	
	<%= f.select("status", [['En proceso', 'proceso'], ['Cancelado', 'cancelado'], ['Embarcado', 'embarcado'], ['Entregado', 'entregado']], {} ,{class: "form-control"}) %><br>
  <%= f.submit "Crear", class: "btn btn-primary" %>
<% end %>
</div>

app/views/embarque/index.html.erb
<h1 class="text-center">Embarques</h1>
<br><br>
<div class="row">
	<%=  link_to "Agregar embarque", new_embarque_path, class: "btn btn-outline-primary offset-sm-6 col-sm-2 "%>
</div>
<div class="row col-sm-12">

	<table class="table table-striped " style="background-color: #b3e6ff" id="myTable">
		<input type="text" class="form-control  col-sm-4" id="myInput" onkeyup="myFunction()" placeholder="Buscar.." title="Type in a name">

		<thead>
			<tr>
				<th scope="col">ID#</th>
	      <th scope="col"># Guia</th>
	      <th scope="col">Transportista</th>
	      <th scope="col"># Ordén</th>
	      <th scope="col">Destino</th>
	      <th scope="col">Cliente</th>
	      <th scope="col">Status</th>
	      <th scope="col">Update</th>
	      <th scope="col">Delete</th>
			</tr>
		</thead>
		<tbody>
			<% if @embarques.empty? %>
				<h3 class="text-center">No hay embarques</h3>
			<% else %>
				<% @embarques.each do|item|%>
					<tr>
						<td scope="col"><%= item.id %></td>
						<td scope="col"><%= item.numero_guia %></td>
						<td scope="col"><%= item.transportista %></td>
						<td scope="col"><%= item.numero_orden %></td>
						<td scope="col"><%= item.destino %></td>
						<td scope="col"><%= item.cliente %></td>
						<td scope="col"><%= item.status %></td>
						<td scope="col"> <%= link_to "Update", edit_embarque_path(item), class: "btn btn-primary" %> </td>
						<td scope="col"> <%= link_to "Delete", embarque_path(item), method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-primary"  %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

app/views/embarque/new.html.erb
<h1 class="text-center">Embarques</h1>
<%= render 'layouts/create_embarque' %>